name: Latest blog post workflow
on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://dev.to/feed/mmustafakapici, https://medium.com/feed/@kolay.zeka'
